# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 451)
        font = QtGui.QFont()
        font.setFamily("Zar")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Saeed/Pictures/Icon/iconfinder_Global_manager_131490.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(255, 140, 120, 48))
        self.play_button.setSizeIncrement(QtCore.QSize(2, 2))
        self.play_button.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.play_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.play_button.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Saeed/Pictures/Icon/iconfinder__magic_wand_1679542.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon1)
        self.play_button.setIconSize(QtCore.QSize(32, 32))
        self.play_button.setAutoDefault(False)
        self.play_button.setDefault(False)
        self.play_button.setFlat(False)
        self.play_button.setObjectName("play_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(315, 20, 161, 41))
        self.label.setObjectName("label")
        self.input_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(130, 70, 350, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        self.input_text.setFont(font)
        self.input_text.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.input_text.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_text.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_text.setLineWidth(1)
        self.input_text.setMidLineWidth(0)
        self.input_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_text.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.input_text.setObjectName("input_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 180, 101, 51))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(80, 230, 401, 141))
        self.output.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.output.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.output.setInputMethodHints(QtCore.Qt.ImhNone)
        self.output.setTextFormat(QtCore.Qt.AutoText)
        self.output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Read me a number"))
        self.play_button.setText(_translate("MainWindow", "شروع"))
        self.label.setText(_translate("MainWindow", "عدد را وارد نمایید"))
        self.label_2.setText(_translate("MainWindow", "عدد شما :"))
        self.output.setText(_translate("MainWindow", "هفصد و شش هزار"))
